/**
 *
 * $Id$
 */
package RESTfulServicePSM.validation;

import RESTfulServicePSM.JAXBAnnotation;
import RESTfulServicePSM.PSMComponentProperty;

/**
 * A sample validator interface for {@link RESTfulServicePSM.JavaSetterFunction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JavaSetterFunctionValidator {
	boolean validate();

	boolean validateSetsProperty(PSMComponentProperty value);
	boolean validateSetterFunctionHasJAXBAnnotation(JAXBAnnotation value);
}
