/**
 *
 * $Id$
 */
package AuthorizationLayerPSM.validation;

import AuthorizationLayerPSM.AnnPSMComponentProperty;
import AuthorizationLayerPSM.AttributeCategory;
import AuthorizationLayerPSM.NewProperty;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link AuthorizationLayerPSM.Attribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributeValidator {
	boolean validate();

	boolean validateAttributeCategory(AttributeCategory value);
	boolean validateValue(EList<String> value);
	boolean validateIsAttributeExistingProperty(AnnPSMComponentProperty value);
	boolean validateIsAttributeNewProperty(NewProperty value);
}
