/**
 *
 * $Id$
 */
package AuthorizationLayerPSM.validation;

import AuthorizationLayerPSM.AnnJavaAlgoResourceModel;
import AuthorizationLayerPSM.AnnJavaResourceModel;
import AuthorizationLayerPSM.AnnJavaResourceModelManager;
import AuthorizationLayerPSM.AuthorizationPerformer;
import AuthorizationLayerPSM.ResourceAccessPolicySet;

/**
 * A sample validator interface for {@link AuthorizationLayerPSM.AuthorizableResource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AuthorizableResourceValidator {
	boolean validate();

	boolean validateIsAuthorizableAlgoModel(AnnJavaAlgoResourceModel value);
	boolean validateIsAuthorizableResourceModel(AnnJavaResourceModel value);
	boolean validateIsAuthorizableModelManager(AnnJavaResourceModelManager value);
	boolean validateHasAuthorizationPerformer(AuthorizationPerformer value);
	boolean validateHasResourceAccessPolicySet(ResourceAccessPolicySet value);
	boolean validateBTrackOwnership(boolean value);
}
