/**
 *
 * $Id$
 */
package AuthorizationLayerPSM.validation;

import AuthorizationLayerPSM.Attribute;
import AuthorizationLayerPSM.Operator;

/**
 * A sample validator interface for {@link AuthorizationLayerPSM.Condition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConditionValidator {
	boolean validate();

	boolean validateOperator(Operator value);
	boolean validateHasLeftSideOperand(Attribute value);
	boolean validateHasRightSideOperand(Attribute value);
}
