/**
 *
 * $Id$
 */
package AuthorizationLayerPSM.validation;

import AuthorizationLayerPSM.CombiningAlgorithm;
import AuthorizationLayerPSM.ResourceAccessPolicy;
import AuthorizationLayerPSM.ResourceAccessPolicySet;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link AuthorizationLayerPSM.ResourceAccessPolicySet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceAccessPolicySetValidator {
	boolean validate();

	boolean validateHasResourceAccessPolicySet(EList<ResourceAccessPolicySet> value);
	boolean validatePolicyCombiningAlgorithm(CombiningAlgorithm value);
	boolean validateHasResourceAccessPolicy(EList<ResourceAccessPolicy> value);
}
