/**
 *
 * $Id$
 */
package AuthorizationLayerPSM.validation;

import AuthorizationLayerPSM.AllowedAction;
import AuthorizationLayerPSM.Condition;
import AuthorizationLayerPSM.RuleType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link AuthorizationLayerPSM.ResourceAccessRule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceAccessRuleValidator {
	boolean validate();

	boolean validateRuleType(RuleType value);
	boolean validateHasMatchCondition(EList<Condition> value);
	boolean validateHasAllowedAction(EList<AllowedAction> value);
}
