/**
 *
 * $Id$
 */
package ServiceCIM.validation;

import ServiceCIM.CRUDActivity;
import ServiceCIM.InputRepresentation;
import ServiceCIM.OutputRepresentation;
import ServiceCIM.Property;
import ServiceCIM.Resource;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ServiceCIM.Resource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceValidator {
	boolean validate();

	boolean validateIsAlgorithmic(boolean value);
	boolean validateName(String value);
	boolean validateHasInputRepresentation(EList<InputRepresentation> value);
	boolean validateHasCRUDActivity(EList<CRUDActivity> value);
	boolean validateHasProperty(EList<Property> value);
	boolean validateHasOutputRepresentation(EList<OutputRepresentation> value);
	boolean validateHasRelatedResource(EList<Resource> value);
	boolean validateIsRelatedResource(EList<Resource> value);
}
