/**
 *
 * $Id$
 */
package ExternalServiceLayerCIM.validation;

import ExternalServiceLayerCIM.ComplexType;

/**
 * A sample validator interface for {@link ExternalServiceLayerCIM.ComplexTypeProperty}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComplexTypePropertyValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateIsUnique(boolean value);
	boolean validateType(String value);
	boolean validateHasPrimitiveType(boolean value);
	boolean validatePropertyHasComplexType(ComplexType value);
}
