/**
 *
 * $Id$
 */
package ExternalServiceLayerCIM.validation;

import ExternalServiceLayerCIM.ComplexTypeProperty;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ExternalServiceLayerCIM.ComplexType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComplexTypeValidator {
	boolean validate();

	boolean validateComplexTypeName(String value);
	boolean validateHasComplexTypeProperties(EList<ComplexTypeProperty> value);
}
