/**
 *
 * $Id$
 */
package ExternalServiceLayerCIM.validation;


/**
 * A sample validator interface for {@link ExternalServiceLayerCIM.QueryParam}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface QueryParamValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateType(String value);
	boolean validateIsAuthToken(boolean value);
	boolean validateAuthTokenToURL(String value);
}
