/**
 *
 * $Id$
 */
package ServiceCIM.validation;

import ServiceCIM.Resource;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ServiceCIM.RESTfulServiceCIM}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RESTfulServiceCIMValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateHasResources(EList<Resource> value);

	boolean validateServiceOutputPath(String value);

	boolean validateServiceDatabaseIP(String value);

	boolean validateServiceDatabasePort(String value);

	boolean validateServiceDatabaseUsername(String value);

	boolean validateServiceDatabasePassword(String value);
}
