/**
 *
 * $Id$
 */
package ServicePSM.validation;

import ServicePSM.HTTPActivity;
import ServicePSM.JAXRSAnnotation;
import ServicePSM.JavaResourceModelManager;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ServicePSM.JavaResourceControllerManager}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JavaResourceControllerManagerValidator {
	boolean validate();

	boolean validateJavaRCManagerHasJAXRSAnnotation(JAXRSAnnotation value);
	boolean validateJavaRCManagerHasHTTPActivity(EList<HTTPActivity> value);
	boolean validateHasAssociatedRMManager(JavaResourceModelManager value);
	boolean validateName(String value);
	boolean validateControllerURI(String value);
	boolean validateParentName(String value);
}
