/**
 *
 * $Id$
 */
package AuthenticationLayerPSM.validation;

import AuthenticationLayerPSM.AnnHTTPActivity;
import AuthenticationLayerPSM.AnnHTTPActivityHandler;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link AuthenticationLayerPSM.AuthenticationMode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AuthenticationModeValidator {
	boolean validate();

	boolean validateHTTPActivityHandlerHasAuthenticationMode(EList<AnnHTTPActivityHandler> value);

	boolean validateHTTPActivityHasAuthenticationMode(EList<AnnHTTPActivity> value);

	boolean validateHTTPActivityHandlerHasAuthenticationMode(AnnHTTPActivityHandler value);
	boolean validateHTTPActivityHasAuthenticationMode(AnnHTTPActivity value);
}
