/**
 *
 * $Id$
 */
package ServicePSM.validation;

import ServicePSM.HTTPActivityFunctionParameter;
import ServicePSM.HTTPActivityHandler;
import ServicePSM.HTTPVerb;
import ServicePSM.HibernateActivity;
import ServicePSM.JAXRSAnnotation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ServicePSM.HTTPActivity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HTTPActivityValidator {
	boolean validate();

	boolean validateIsMappedToHibernateActivity(HibernateActivity value);
	boolean validateHasHTTPActivityParameter(EList<HTTPActivityFunctionParameter> value);
	boolean validateActivityHTTPVerb(HTTPVerb value);
	boolean validateName(String value);
	boolean validateHTTPActivityURI(String value);
	boolean validateHasHTTPActivityHandler(HTTPActivityHandler value);
	boolean validateHTTPActivityHasJAXRSAnnotation(EList<JAXRSAnnotation> value);
}
