/**
 *
 * $Id$
 */
package AuthenticationLayerCIM.validation;

import AuthenticationLayerCIM.AnnotatedElement;
import AuthenticationLayerCIM.Annotation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link AuthenticationLayerCIM.AnnotationModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnnotationModelValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateHasAnnotatedElement(EList<AnnotatedElement> value);
	boolean validateHasAnnotation(EList<Annotation> value);
}
