/**
 *
 * $Id$
 */
package ExternalServiceLayerCIM.validation;

import ExternalServiceLayerCIM.AnnAlgoResource;
import ExternalServiceLayerCIM.TargetRESTService;

/**
 * A sample validator interface for {@link ExternalServiceLayerCIM.RESTClientResource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RESTClientResourceValidator {
	boolean validate();

	boolean validateTargetsService(TargetRESTService value);
	boolean validateIsRESTClientResource(AnnAlgoResource value);
}
