/**
 *
 * $Id$
 */
package MDEMigratorPSMMetamodel.validation;

import MDEMigratorPSMMetamodel.SourceColumn;
import MDEMigratorPSMMetamodel.TargetRelation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link MDEMigratorPSMMetamodel.ParentMapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParentMappingValidator {
	boolean validate();

	boolean validateHasParentTargetRelation(TargetRelation value);
	boolean validateHasForeignKeyColumn(EList<SourceColumn> value);
	boolean validateSourceRelationFKMappingName(String value);
}
