/**
 *
 * $Id$
 */
package MDEMigratorPSMMetamodel.validation;

import MDEMigratorPSMMetamodel.SourceColumn;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link MDEMigratorPSMMetamodel.SourceRelation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SourceRelationValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateHasSourceColumn(EList<SourceColumn> value);
	boolean validateHasPrimaryKeyColumn(EList<SourceColumn> value);
}
