/**
 *
 * $Id$
 */
package MDEMigratorPSMMetamodel.validation;

import MDEMigratorPSMMetamodel.SourceColumn;

import RESTfulServicePSM.PSMComponentProperty;

/**
 * A sample validator interface for {@link MDEMigratorPSMMetamodel.TargetColumn}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TargetColumnValidator {
	boolean validate();

	boolean validateColumnMappingName(String value);
	boolean validateIsMappedFromColumn(SourceColumn value);
	boolean validateIsAnnotatedPSMComponentProperty(PSMComponentProperty value);
}
