/**
 *
 * $Id$
 */
package MDEMigratorPSMMetamodel.validation;

import MDEMigratorPSMMetamodel.ParentMapping;
import MDEMigratorPSMMetamodel.SourceRelation;
import MDEMigratorPSMMetamodel.TargetColumn;

import RESTfulServicePSM.JavaResourceModel;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link MDEMigratorPSMMetamodel.TargetRelation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TargetRelationValidator {
	boolean validate();

	boolean validateRelationMappingName(String value);
	boolean validateBIsScheduledToLoad(boolean value);
	boolean validateHasTargetColumn(EList<TargetColumn> value);
	boolean validateIsMappedFromRelation(SourceRelation value);
	boolean validateIsTargetRelationJavaResourceModel(JavaResourceModel value);
	boolean validateMigrationOrderIndex(int value);
	boolean validateBHasParentMapping(boolean value);
	boolean validateHasParentMapping(EList<ParentMapping> value);
}
