/**
 *
 * $Id$
 */
package ServicePIM.validation;

import ServicePIM.AlgoResourceModel;
import ServicePIM.ResourceControllerCRUDActivity;

/**
 * A sample validator interface for {@link ServicePIM.AlgoResourceController}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AlgoResourceControllerValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateParentName(String value);
	boolean validateControllerURI(String value);
	boolean validateHasAssociatedAlgoModel(AlgoResourceModel value);
	boolean validateAlgoControllerHasCRUDActivity(ResourceControllerCRUDActivity value);
}
