/**
 *
 * $Id$
 */
package ServicePIM.validation;

import ServicePIM.AlgoResourceController;
import ServicePIM.CRUDVerb;
import ServicePIM.LinkType;
import ServicePIM.ResourceController;
import ServicePIM.ResourceControllerManager;

/**
 * A sample validator interface for {@link ServicePIM.HypermediaLink}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HypermediaLinkValidator {
	boolean validate();

	boolean validateLinkCRUDVerb(CRUDVerb value);
	boolean validateLinkType(LinkType value);
	boolean validateHasTargetAlgoController(AlgoResourceController value);
	boolean validateHasTargetRCManager(ResourceControllerManager value);
	boolean validateHasTargetRController(ResourceController value);
}
