/**
 *
 * $Id$
 */
package ServicePIM.validation;

import ServicePIM.ResourceControllerCRUDActivity;
import ServicePIM.ResourceModelManager;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ServicePIM.ResourceControllerManager}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceControllerManagerValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateControllerURI(String value);
	boolean validateHasAssociatedRMManager(ResourceModelManager value);
	boolean validateRCManagerHasCRUDActivity(EList<ResourceControllerCRUDActivity> value);
	boolean validateParentName(String value);
}
