/**
 *
 * $Id$
 */
package ServicePIM.validation;

import ServicePIM.AlgoResourceController;
import ServicePIM.AlgoResourceModel;
import ServicePIM.DatabaseController;
import ServicePIM.RDBMSTable;
import ServicePIM.ResourceController;
import ServicePIM.ResourceControllerManager;
import ServicePIM.ResourceModel;
import ServicePIM.ResourceModelManager;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ServicePIM.RESTfulServicePIM}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RESTfulServicePIMValidator {
	boolean validate();

	boolean validateHasResourceModel(EList<ResourceModel> value);
	boolean validateHasResourceModelManager(EList<ResourceModelManager> value);
	boolean validateHasResourceController(EList<ResourceController> value);
	boolean validateHasResourceControllerManager(EList<ResourceControllerManager> value);
	boolean validateHasAlgoResourceModel(EList<AlgoResourceModel> value);
	boolean validateHasAlgoResourceController(EList<AlgoResourceController> value);
	boolean validateHasRDBMSTable(EList<RDBMSTable> value);
	boolean validateHasDatabaseController(DatabaseController value);
	boolean validateName(String value);
}
