/**
 *
 * $Id$
 */
package AuthenticationLayerCIM.validation;

import AuthenticationLayerCIM.AnnProperty;
import AuthenticationLayerCIM.Property;

/**
 * A sample validator interface for {@link AuthenticationLayerCIM.AuthenticationToken}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AuthenticationTokenValidator {
	boolean validate();

	boolean validatePropertyAuthenticationToken(Property value);
	boolean validateName(String value);
	boolean validateType(String value);
	boolean validateBIsUnique(boolean value);

	boolean validatePropertyAuthenticationToken(AnnProperty value);
}
