/**
 *
 * $Id$
 */
package ExternalServiceLayerPSM.validation;

import ExternalServiceLayerPSM.AnnHTTPActivity;
import ExternalServiceLayerPSM.JavaRESTClientHTTPActivityHandler;
import ExternalServiceLayerPSM.QueryParam;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ExternalServiceLayerPSM.JavaRESTClientHTTPActivity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JavaRESTClientHTTPActivityValidator {
	boolean validate();

	boolean validateHasJavaRESTClientHTTPActivityHandler(JavaRESTClientHTTPActivityHandler value);
	boolean validateHasQueryParam(EList<QueryParam> value);
	boolean validateIsJavaRESTClientHTTPActivity(AnnHTTPActivity value);
}
