/**
 *
 * $Id$
 */
package SearchLayerPSM.validation;

import SearchLayerPSM.AnnotatedElement;
import SearchLayerPSM.Annotation;

import ServicePSM.RESTfulServicePSM;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SearchLayerPSM.AnnotationModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnnotationModelValidator {
	boolean validate();

	boolean validateHasAnnotatedElement(EList<AnnotatedElement> value);
	boolean validateHasAnnotation(EList<Annotation> value);
	boolean validateName(String value);
	boolean validateAnnotatesRESTfulServicePSM(RESTfulServicePSM value);
}
