/**
 *
 * $Id$
 */
package AnnotationLayerStack.validation;

import AuthenticationLayerPSM.AnnotationModel;

import ServicePSM.RESTfulServicePSM;

/**
 * A sample validator interface for {@link AnnotationLayerStack.AnnotationStack}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnnotationStackValidator {
	boolean validate();

	boolean validateHasAuthenticationLayer(AnnotationModel value);
	boolean validateBHasAuthenticationAnnotation(boolean value);
	boolean validateHasCorePSM(RESTfulServicePSM value);
	boolean validateHasSearchLayer(SearchLayerPSM.AnnotationModel value);
	boolean validateBHasSearchLayer(boolean value);
}
