/**
 *
 * $Id$
 */
package AuthenticationLayerCIM.validation;

import ServiceCIM.CRUDActivity;
import ServiceCIM.Resource;

/**
 * A sample validator interface for {@link AuthenticationLayerCIM.AnnCRUDActivity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnnCRUDActivityValidator {
	boolean validate();

	boolean validateAnnotatesCRUDActivity(CRUDActivity value);

	boolean validateName(String value);

	boolean validateBelongsToResource(Resource value);
}
