/**
 *
 * $Id$
 */
package ServicePIM.validation;

import ServicePIM.AlgoResourceModel;
import ServicePIM.GetterFunction;
import ServicePIM.PIMComponentProperty;
import ServicePIM.RepresentationMarshallingFunction;
import ServicePIM.RepresentationParseFunction;
import ServicePIM.ResourceInputRepresentation;
import ServicePIM.ResourceOutputRepresentation;
import ServicePIM.SetterFunction;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ServicePIM.AlgoResourceModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AlgoResourceModelValidator {
	boolean validate();

	boolean validateParentName(String value);
	boolean validateName(String value);
	boolean validateAlgoModelHasInputRepresentation(EList<ResourceInputRepresentation> value);
	boolean validateAlgoModelHasOutputRepresentation(EList<ResourceOutputRepresentation> value);
	boolean validateAlgoModelHasProperty(PIMComponentProperty value);
	boolean validateAlgoModelHasSetter(SetterFunction value);
	boolean validateAlgoModelHasGetter(GetterFunction value);
	boolean validateHasRelatedAlgoModel(EList<AlgoResourceModel> value);
	boolean validateIsRelatedAlgoModel(EList<AlgoResourceModel> value);
	boolean validateAlgoModelHasParseFunction(EList<RepresentationParseFunction> value);
	boolean validateAlgoModelHasMarshallingFunction(EList<RepresentationMarshallingFunction> value);
}
