/**
 *
 * $Id$
 */
package ServicePIM.validation;

import ServicePIM.GetterFunction;
import ServicePIM.PIMComponentProperty;
import ServicePIM.RepresentationMarshallingFunction;
import ServicePIM.RepresentationParseFunction;
import ServicePIM.ResourceInputRepresentation;
import ServicePIM.ResourceModel;
import ServicePIM.ResourceOutputRepresentation;
import ServicePIM.SetterFunction;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ServicePIM.ResourceModelManager}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceModelManagerValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateParentName(String value);
	boolean validateHasRelatedModel(ResourceModel value);
	boolean validateRMManagerHasInputRepresentation(EList<ResourceInputRepresentation> value);
	boolean validateRMManagerHasOutputRepresentation(EList<ResourceOutputRepresentation> value);
	boolean validateHasRMManagerProperty(PIMComponentProperty value);
	boolean validateRMManagerHasSetter(SetterFunction value);
	boolean validateRMManagerHasGetter(GetterFunction value);
	boolean validateRMManagerHasParseFunction(EList<RepresentationParseFunction> value);
	boolean validateRMManagerHasMarshallingFunction(EList<RepresentationMarshallingFunction> value);
}
