/**
 *
 * $Id$
 */
package ServicePSM.validation;

import ServicePSM.HibernateAnnotation;
import ServicePSM.JAXBAnnotation;
import ServicePSM.JavaAlgoResourceModel;
import ServicePSM.JavaGetterFunction;
import ServicePSM.JavaResourceModelManager;
import ServicePSM.JavaSetterFunction;
import ServicePSM.PSMComponentProperty;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ServicePSM.JavaResourceModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JavaResourceModelValidator {
	boolean validate();

	boolean validateJavaRModelHasJAXBAnnotation(JAXBAnnotation value);
	boolean validateJavaRModelHasProperty(EList<PSMComponentProperty> value);
	boolean validateHasRelatedJavaRMManager(EList<JavaResourceModelManager> value);
	boolean validateJavaRModelHasHibernateAnnotation(EList<HibernateAnnotation> value);
	boolean validateJavaRModelHasSetter(EList<JavaSetterFunction> value);
	boolean validateJavaRModelHasGetter(EList<JavaGetterFunction> value);
	boolean validateHasRelatedJavaAlgoModel(EList<JavaAlgoResourceModel> value);
	boolean validateName(String value);
	boolean validateParentName(String value);
}
