/**
 *
 * $Id$
 */
package ServicePSM.validation;

import ServicePSM.HTTPActivity;
import ServicePSM.JAXRSAnnotation;
import ServicePSM.JavaResourceModel;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ServicePSM.JavaResourceController}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JavaResourceControllerValidator {
	boolean validate();

	boolean validateJavaRControllerHasJAXRSAnnotation(JAXRSAnnotation value);
	boolean validateJavaRControllerHasHTTPActivity(EList<HTTPActivity> value);
	boolean validateHasAssociatedJavaRModel(JavaResourceModel value);
	boolean validateName(String value);
	boolean validateControllerURI(String value);
	boolean validateParentName(String value);
}
